#!/usr/bin/env bash

NOTES_DIR="${NOTES:-$HOME/Documents/}/daily"

mkdir -p "$NOTES_DIR"
cd "$NOTES_DIR"

full_date=$(date '+%Y.%m.%d.%H.%M')
IFS=. read -r year month day hour minute <<< "$full_date"

file="$year.$month.$day.md"
echo "# $hour:$minute" >> "$file"
exec ${EDITOR-nano} "$file"
